name: build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11, macos-14, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}
          path: wheelhouse/*
